title: <p align="center"> Shriya Seshadri </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="Desktop/Shriya Seshadri Resume.pdf">Resume</a> |
  <a href="www.linkedin.com/in/shriya- seshadri-588201191">LinkedIn</a> |
  <a href="https://github.com/shriyaS5">GitHub</a>
  
  <br>   
  "I'm working as a technical analyst with conduent business india services."
  'I have had a experience of more than 1 year with SQL development."
  <br>
  </p>



theme: jekyll-theme-minimal
